src/Entity/Performances.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PerformancesRepository")
 */
class Performances
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $laugh;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $dream;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $marvel_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLaugh(): ?string
    {
        return $this->laugh;
    }

    public function setLaugh(?string $laugh): self
    {
        $this->laugh = $laugh;

        return $this;
    }

    public function getDream(): ?string
    {
        return $this->dream;
    }

    public function setDream(?string $dream): self
    {
        $this->dream = $dream;

        return $this;
    }

    public function getMarvelAt(): ?string
    {
        return $this->marvel_at;
    }

    public function setMarvelAt(?string $marvel_at): self
    {
        $this->marvel_at = $marvel_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\AboutUsRepository;
use App\Repository\PerformancesRepository;
use App\Repository\PricesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(PerformancesRepository $performances, AboutUsRepository $aboutus, PricesRepository $prices)
    {
        return $this->render('home/index.html.twig', [
            'performances' => $performances->findOneBy(['id' => 1]),
            'aboutus' => $aboutus->findOneBy(['id'=> 1]),
            'prices' => $prices->findAll(),
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wild Circus{% endblock %}

{% block body %}
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">

        <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

        <link href="carousel.css" rel="stylesheet">
    </head>
    <body>
    <!-- Partie NAVBAR-->

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#"><img src="assets/img/logo.png" height="50px"/></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#performances">Performances <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#aboutus">About US</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link disabled" href="#aboutus">Prices</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link disabled" href="#contactus">Contact</a>
                    </li>
                </ul>

                {% if app.user is not null %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_logout') }}">Sign Out</a>
                    </li>
                    {% else %}
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link " href="{{ path('app_login') }}">Log In</a>
                            </li>
                        </ul>
                </ul>
            </div>
            {% endif %}

        </nav>
    </header>
    <main role="main">
        <!-- Partie Carousel-->

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="first-slide" src="/assets/img/Circuswalpaper.jpg" alt="First slide">
                    <div class="container">
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="second-slide" src="/assets/img/circus1.jpg" alt="Second slide">
                    <div class="container">
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="third-slide" src="/assets/img/circus2.jpg" alt="Third slide">
                    <div class="container">
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <hr class="featurette-divider">

        <!-- Partie PERFORMANCES-->
        <div class="container marketing" id="performances">
            <div class="row">
                <div class="col-lg-4">
                    <img class="rounded-circle" src="assets/img/perf1.jpeg" alt="Generic placeholder image" width="140" height="140">
                    <h2>LAUGH</h2>
                    <p>{{ performances.laugh }}</p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="rounded-circle" src="assets/img/perf2.jpeg" alt="Generic placeholder image" width="140" height="140">
                    <h2>DREAM</h2>
                    <p>{{ performances.dream }}</p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="rounded-circle" src="assets/img/perf3.jpeg" alt="Generic placeholder image" width="140" height="140">
                    <h2>MARVEL AT</h2>
                    <p>{{ performances.marvelAt }}</p>
                </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->


            <!-- ABOUT US & PRICES -->

            <hr class="featurette-divider">

            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading" id="aboutus">ABOUT US</h2>
                    <p>{{ aboutus.description }}</p>
                </div>
                <div class="col-md-5">
                    <img class="featurette-image img-fluid mx-auto" src="assets/img/aboutus.jpg" alt="Generic placeholder image">
                </div>
            </div>

            <hr class="featurette-divider">
            <h2 class="featurette-heading" id="prices">PRICES</h2>

            <table class="table table-light table-hover">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Prix</th>
                </tr>
                </thead>
                <tbody>

                {% for price in prices %}
                    <tr>
                        <th scope="row"></th>
                        <td>{{ price.service }}</td>
                        <td>{{ price.price }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>


            <!--Section: Contact-->
            <section class="mb-4">

                <h2 class="h1-responsive font-weight-bold text-center my-4" id="contactus">Contact us</h2>
                <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
                    a matter of hours to help you.</p>

                <div class="row">

                    <div class="col-md-9 mb-md-0 mb-5">
                        <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                            <div class="row">

                                <div class="col-md-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="name" name="name" class="form-control">
                                        <label for="name" class="">Your name</label>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="md-form mb-0">
                                        <input type="text" id="email" name="email" class="form-control">
                                        <label for="email" class="">Your email</label>
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="md-form mb-0">
                                        <input type="text" id="subject" name="subject" class="form-control">
                                        <label for="subject" class="">Subject</label>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md-12">

                                    <div class="md-form">
                                        <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                                        <label for="message">Your message</label>
                                    </div>

                                </div>
                            </div>

                        </form>

                        <div class="text-center text-md-left">
                            <a class="btn btn-primary" style="background-color: #2e3136 !important;" onclick="document.getElementById('contact-form').submit();">Send</a>
                        </div>
                        <div class="status"></div>
                    </div>

                    <div class="col-md-3 text-center">
                        <ul class="list-unstyled mb-0">
                            <li><i class="fas fa-map-marker-alt fa-2x"></i>
                                <p>San Francisco, CA 94126, USA</p>
                            </li>

                            <li><i class="fas fa-phone mt-4 fa-2x"></i>
                                <p>03 50 93 59 32</p>
                            </li>

                            <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                                <p>contact@wcs.com</p>
                            </li>
                        </ul>
                    </div>

                </div>

            </section>

            <hr class="featurette-divider">

            <!-- Footer -->
            <footer class="page-footer font-small special-color-dark pt-4" style="background-color: black !important;">

                <div class="container">

                    <ul class="list-unstyled list-inline text-center">
                        <li class="list-inline-item">
                            <a class="btn-floating btn-fb mx-1">
                                <i class="fab fa-facebook-f"> </i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-tw mx-1">
                                <i class="fab fa-twitter"> </i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-gplus mx-1">
                                <i class="fab fa-google-plus-g"> </i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-li mx-1">
                                <i class="fab fa-linkedin-in"> </i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-dribbble mx-1">
                                <i class="fab fa-dribbble"> </i>
                            </a>
                        </li>
                    </ul>

                </div>

                <!-- Copyright -->
                <div class="footer-copyright text-center py-3">© 2020 Copyright:
                    <a href="https://mdbootstrap.com/education/bootstrap/"> Cem Society</a>
                </div>
                <!-- Copyright -->

            </footer>

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    </body>
    </html>

{% endblock %}